image: ubuntu:22.04

test:
  script:
    - apt-get update
    - apt-get install -y sqlite3 libsqlite3-dev redis-server snapd
    - systemctl start snapd.service
    - snap install flutter --classic
    - flutter pub get
    - flutter analyze .
    - redis-server&
    - flutter test
