---
image: gitlab.cosmian.com:5000/core/ci-flutter:latest

services:
  - redis:latest

stages:
  - test
  - publish
  - pack

.test:
  stage: test
  script:
    - flutter pub get
    - flutter analyze .
    - flutter test --concurrency 1
    - dart benchmark/cloudproof_benchmark.dart

test_linux:
  extends: .test

test_mac:
  extends: .test
  tags:
    - mac

publish:
  stage: publish
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+.\d+.\d+$/
  before_script:
    - mkdir -p ~/.config/dart
    - echo "$DART_CREDENTIALS" > ~/.config/dart/pub-credentials.json
  script:
    - dart pub publish -f

pack:
  stage: pack
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+.\d+.\d+$/
  script:
    - git archive --verbose --format=zip --output=${CI_PROJECT_NAME}_${CI_COMMIT_TAG}.zip HEAD
  artifacts:
    name: ${CI_PROJECT_NAME}_${CI_COMMIT_TAG}
    paths:
      - ${CI_PROJECT_NAME}_${CI_COMMIT_TAG}.zip
    expire_in: 3 mos
