---
image: gitlab.cosmian.com:5000/core/ci-flutter:latest

stages:
  - test
  - pack

test:
  stage: test
  script:
    - flutter pub get
    - flutter analyze .
    - redis-server&
    - flutter test

pack:
  stage: pack
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+.\d+.\d+$/
  script:
    - git archive --verbose --format=zip --output=${CI_PROJECT_NAME}_${CI_COMMIT_TAG}.zip HEAD
  artifacts:
    name: ${CI_PROJECT_NAME}_${CI_COMMIT_TAG}
    paths:
      - ${CI_PROJECT_NAME}_${CI_COMMIT_TAG}.zip
    expire_in: 3 mos
