image: ubuntu:22.04

stages:
  - test
  - pack

test:
  stage: test
  script:
    - apt-get update
    - apt-get install -y sqlite3 libsqlite3-dev redis-server wget xz-utils git
    - wget https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.3.3-stable.tar.xz -O /tmp/flutter_linux_3.3.3-stable.tar.xz
    - tar xf /tmp/flutter_linux_3.3.3-stable.tar.xz --directory /tmp
    - git config --global --add safe.directory /tmp/flutter
    - export PATH="$PATH:/tmp/flutter/bin"
    - flutter doctor
    - flutter pub get
    - flutter analyze .
    - redis-server&
    - flutter test

pack:
  stage: pack
  script:
    - git archive --verbose --format=zip --output=${CI_PROJECT_NAME}_${CI_COMMIT_TAG}.zip HEAD
  artifacts:
    name: '${CI_PROJECT_NAME}_${CI_COMMIT_TAG}'
    paths:
      - ${CI_PROJECT_NAME}_${CI_COMMIT_TAG}.zip
    expire_in: 3 mos
