---
image: gitlab.cosmian.com:5000/core/ci-flutter:latest

services:
  - redis:latest

stages:
  - test
  - pack
  - publish

.test:
  stage: test
  script:
    - flutter pub get
    - flutter analyze .
    - flutter test
    - dart benchmark/cloudproof_benchmark.dart

test_linux:
  extends: .test

test_mac:
  extends: .test
  tags:
    - mac

pack:
  stage: pack
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+.\d+.\d+$/
  script:
    - git archive --verbose --format=zip --output=${CI_PROJECT_NAME}_${CI_COMMIT_TAG}.zip HEAD
  artifacts:
    name: ${CI_PROJECT_NAME}_${CI_COMMIT_TAG}
    paths:
      - ${CI_PROJECT_NAME}_${CI_COMMIT_TAG}.zip
    expire_in: 3 mos

publish:
  stage: publish
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+.\d+.\d+$/
  script:
    - dart pub publish
